"""Training utilities for the HybridSignalNet."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Tuple

import numpy as np
import pandas as pd

from .models import FeatureNormalizer, HybridSignalNet

DATA_COLUMNS = [
    "pattern_confidence",
    "pattern_velocity",
    "atr",
    "spread",
    "historical_win_rate",
    "nn_score",
]
TARGET_COLUMN = "final_score"


def load_dataset(dataset_path: Path) -> Tuple[np.ndarray, np.ndarray]:
    if not dataset_path.exists():
        raise FileNotFoundError(dataset_path)
    df = pd.read_csv(dataset_path, sep=";")
    df = df.dropna(subset=DATA_COLUMNS + [TARGET_COLUMN])
    features = df[DATA_COLUMNS].to_numpy(dtype=np.float32)
    labels = (df[TARGET_COLUMN] > 0.5).astype(np.float32)
    return features, labels


def train_model(dataset_path: Path, epochs: int = 400, lr: float = 0.01) -> Tuple[HybridSignalNet, FeatureNormalizer]:
    features, labels = load_dataset(dataset_path)
    normalizer = FeatureNormalizer()
    normalizer.fit(features)
    features_norm = normalizer.transform(features)

    model = HybridSignalNet(input_dim=features_norm.shape[1], hidden_dim=32)
    model.train(features_norm, labels, epochs=epochs, lr=lr)
    return model, normalizer


def cli() -> None:
    parser = argparse.ArgumentParser(description="Train HybridSignalNet and export weights")
    parser.add_argument("dataset", type=Path, help="Path to CSV generated by MLStrategy.mq5")
    parser.add_argument("--output", type=Path, default=Path("artifacts/hybrid_model.json"))
    parser.add_argument("--weights", type=Path, default=Path("artifacts/hybrid_model.weights"))
    parser.add_argument("--epochs", type=int, default=400)
    parser.add_argument("--lr", type=float, default=0.01)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.weights.parent.mkdir(parents=True, exist_ok=True)

    model, normalizer = train_model(args.dataset, epochs=args.epochs, lr=args.lr)
    model.save(args.output, normalizer)
    model.export_for_mql5(args.weights)
    print(f"Saved JSON weights to {args.output}")
    print(f"Exported MQL weights to {args.weights}")


if __name__ == "__main__":
    cli()
